node {
  stage('git checkout') {
    git branch: 'deploy-k8s-gcp', url: 'https://github.com/mazma1/microservice-app-example'
  }

  stage('archive') {
    archiveArtifacts artifacts: '*, users-api/'
  }

  stage('build image') {
    sh '''
      cd ${WORKSPACE}/users-api
      REPO="users-api-service"
      #Build container images using Dockerfile
      docker build --no-cache -t ${REPO}:${BUILD_NUMBER} .
    '''
  }

  stage('login to gcr') {
    withCredentials([string(credentialsId: 'GCLOUD-SERVICE-KEY', variable: 'GCLOUD_SERVICE_KEY')]) {
      sh '''
        echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${WORKSPACE}/gcloud-service-key.json
        docker login -u _json_key -p "$(cat ${WORKSPACE}/gcloud-service-key.json)" https://gcr.io
      '''
    }
  }

  stage('push image to GCR') {
    withCredentials([string(credentialsId: 'REGISTRY-URL', variable: 'REGISTRY_URL')]) {
      sh '''
        REG_ADDRESS="${REGISTRY_URL}"
        REPO="users-api-service"
        #Tag the build with BUILD_NUMBER version
        docker tag ${REPO}:${BUILD_NUMBER} ${REG_ADDRESS}/${REPO}:${BUILD_NUMBER}
        #Publish image
        docker push ${REG_ADDRESS}/${REPO}:${BUILD_NUMBER}
      '''
    }
  }

  stage('deploy to Kubernetes cluster') {
    withCredentials([
      string(credentialsId: 'REGISTRY-URL', variable: 'REGISTRY_URL'),
      string(credentialsId: 'CLUSTER-NAME', variable: 'CLUSTER_NAME'),
      string(credentialsId: 'SERVER-URL', variable: 'SERVER_URL')
    ]) {
      withKubeConfig(caCertificate: '', contextName: "${CLUSTER_NAME}", credentialsId: 'KUBERNETES', serverUrl: "${SERVER_URL}") {
        sh '''
          REPO="users-api-service"
          NEW_SERVICE_IMAGE="${REGISTRY_URL}/${REPO}:${BUILD_NUMBER}"
          #Update the image of the users-api container
          kubectl set image deployment/users-api users-api=${NEW_SERVICE_IMAGE}
        '''
      }
    }
  }
}