apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: microservice-app-example
  name: users-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice-app-example
        service: users-api
    spec:
      containers:
      - env:
        - name: JWT_SECRET
          value: myfancysecret
        - name: SERVER_PORT
          value: "8083"
        - name: SPRING_ZIPKIN_BASE_URL
          value: http://zipkin:9411
        image: 791699432634.dkr.ecr.eu-central-1.amazonaws.com/users-api-service:12
        name: users-api
        ports:
        - containerPort: 8083
        imagePullPolicy: Always
      restartPolicy: Always
